// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh8GaZ7u9u9nsMcXgkYjlhMV3MQoLrLCs',
    appId: '1:990122522024:web:15a4c8932a5680e359199d',
    messagingSenderId: '990122522024',
    projectId: 'sheraccerp-8495a',
    authDomain: 'sheraccerp-8495a.firebaseapp.com',
    storageBucket: 'sheraccerp-8495a.appspot.com',
    measurementId: 'G-ZTVFDPN3DL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOWunn7CUMArpzfMyjEILcn6jnC-g8IUY',
    appId: '1:990122522024:android:153bc28453cc2d5f59199d',
    messagingSenderId: '990122522024',
    projectId: 'sheraccerp-8495a',
    storageBucket: 'sheraccerp-8495a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMD5e_QPjlssBR8VrHg3kmlvXzJlQwfBU',
    appId: '1:990122522024:ios:6c6a1f606330135459199d',
    messagingSenderId: '990122522024',
    projectId: 'sheraccerp-8495a',
    storageBucket: 'sheraccerp-8495a.appspot.com',
    iosClientId: '990122522024-q03uvfs16hfg0gnurm2akvin2lstc91a.apps.googleusercontent.com',
    iosBundleId: 'com.shersoft.sheraccerp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMD5e_QPjlssBR8VrHg3kmlvXzJlQwfBU',
    appId: '1:990122522024:ios:68689f34afdc06d759199d',
    messagingSenderId: '990122522024',
    projectId: 'sheraccerp-8495a',
    storageBucket: 'sheraccerp-8495a.appspot.com',
    iosClientId: '990122522024-bv9dd3lth5c57qsogabc9ccg6vo1bif7.apps.googleusercontent.com',
    iosBundleId: 'com.shersoft.sheraccerp.RunnerTests',
  );
}
