import 'package:flutter/material.dart';

const kPrimaryColor = Color(0xFF0008B3);
const bagroundColor = Color(0xffF2F2F2);
const white = Colors.white;
const whiteDark = Colors.white54;
const black = Colors.black;
const blue = Colors.blue;
const black54 = Colors.black54;
const indigoAccent = Colors.indigoAccent;
const blueAccent = Colors.blueAccent;
const teal = Colors.teal;
const grey = Colors.grey;
const green = Colors.green;
const red = Colors.red;
const redAccent = Colors.redAccent;

const greenDark = Color(0xFF1E5B20);
const kPrimaryLightColor = Color(0xFFE8EAF6);
const kPrimaryDarkColor = Color(0xFF1A237E);
const transparent = Color(0x00000000);
const Color firebaseNavy = Color(0xFF2C384A);
const Color firebaseOrange = Color(0xFFF57C00);
const Color firebaseAmber = Color(0xFFFFA000);
const Color firebaseYellow = Color(0xFFFFCA28);
const Color firebaseGrey = Color(0xFFECEFF1);
const Color googleBackground = Color(0xFF4285F4);
const Color orange = Color(0xFFFFC100);
const Color lightBlue = Color(0xFF91FAFF);
const Color cyan = Color(0xFF00D1FF);
const Color cerulean = Color(0xFF00BCFF);

const Color amber = Colors.amber;
const Color amberAccent = Colors.amberAccent;
const Color blueGrey = Color(0xFF607D8B);
const Color lightBlue1 = Colors.lightBlue;
const Color lightBlueAccent = Colors.lightBlueAccent;
const Color brown = Colors.brown;
const Color cyanAccent = Colors.cyanAccent;
const Color lime = Colors.lime;
const Color pink = Colors.pink;
const Color purple = Colors.purple;
const Color purple1 =Color(0xFFAA90E6);
const Color bbGreen =Color(0xFF91BA59);
const Color tealAccent = Colors.tealAccent;
const Color yellowAccent = Colors.yellowAccent;
